### PR TITLE
Fix aarch64 cross build

### PR DESCRIPTION
**Pull request by L1ghtmann**
Tested successfully on GitHub actions. 

Before:
- Redef error (re header change)
- Working C compiler test fail (re explicit target/arch flags)

### CODE REVIEW

**Comment by tpoechtrager** [comment]
`-target` and `-arch` is wrong in `configure.ac`. This must be done in a compiler wrapper.

**Comment by L1ghtmann** [comment]
I apologize, I'm not too familiar with autogen...would you mind elaborating? `autoconf` appears to generate the intended `configure` script.

**Comment by tpoechtrager** [comment]
It builds fine on an `aarch64` host.
If it doesn't compile with your cross compiler then there is most likely something wrong with your setup.
    
    # uname -a
    Linux rockpro64 6.4.7-1-MANJARO-ARM #1 SMP PREEMPT Sun Jul 30 21:28:41 UTC 2023 aarch64 GNU/Linux
    
    # ./ld64/src/ld/ld -v
    @(#)PROGRAM:ld  PROJECT:ld64-609
    BUILD 19:47:29 Sep  6 2023
    configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em (tvOS)

The cross compilation flags do not belong in `configure.ac`.

`CC="clang -target <target>" CXX=clang++ -target <target>" ./configure --host=aarch64-[...]`

Is what you should do instead.

**Comment by L1ghtmann** [comment]
I'm compiling an aarch64-apple-darwin14 target from x86_64-linux-gnu for an aarch64-linux-gnu host using Apple's LLVM/Clang. 

After successfully building libtapi for aarch64, I attempt to build cctools-port with
```
git clone --depth=1 https://github.com/tpoechtrager/cctools-port
./cctools-port/cctools/configure --prefix="$HOME/work/linux/iphone/" \
	--build=x86_64-linux-gnu \
	--host=aarch64-linux-gnu \
	--target=aarch64-apple-darwin14 \
	--enable-tapi-support \
	--with-libtapi="$HOME/work/linux/iphone/" \
	--program-prefix="" \
	CC="$HOME/work/llvm-project/llvm-project/build-host/bin/clang" \
	CXX="$HOME/work/llvm-project/llvm-project/build-host/bin/clang++" \
	CXXABI_LIB="-l:libc++abi.a" \
	LDFLAGS="-Wl,-rpath,'\$\$ORIGIN/../lib' -Wl,-z,origin" 
```

And I get
```
configure:14617: checking tapi/tapi.h and libtapi support
configure:14642: /home/runner/work/llvm-project/llvm-project/build-host/bin/clang++ -o conftest -O3 -std=c++1z  -DLD64_VERSION_NUM=609 -fblocks -D__arm64__  -isystem /home/runner/work/linux/iphone//include  -isystem /home/runner/work/linux/iphone//include -Wl,-rpath,'$$ORIGIN/../lib' -Wl,-z,origin -Wl,-rpath,/usr/lib/llvm-11/lib,--enable-new-dtags -L/home/runner/work/linux/iphone//lib -Wl,-rpath,/home/runner/work/linux/iphone//lib,--enable-new-dtags -Wl,-rpath,/home/runner/work/linux/iphone//lib64,--enable-new-dtags -Wl,-rpath,/home/runner/work/linux/iphone//lib32,--enable-new-dtags conftest.cpp  -ltapi >&5
/usr/bin/ld: skipping incompatible /home/runner/work/linux/iphone//lib/libtapi.so when searching for -ltapi
/usr/bin/ld: cannot find -ltapi
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
configure:14642: $? = 1
```
because it appears to be targeting x64 still. 
---
Based on your comment above, should I close this PR?

**Comment by tpoechtrager** [comment]
No need to close it yet. Why do you not build on the aarch64 host? Would
make it a lot easier.

**Comment by L1ghtmann** [comment]
Okay. And I'm building on GitHub CI and using docker/qemu is painfully slow.

**Comment by tpoechtrager** [comment]
I took me a while but I was able to cross compile it with **crosstool-NG** + this script.

    #!/bin/bash
    
    # Script should be placed in the same binary directory as GCC is in
    # bin/aarch64-unknown-linux-gcc
    # bin/aarch64-unknown-linux-clang
    
    TARGET_ARCH="aarch64-unknown-linux-gnu"
    
    GCC_VERSION="13.2.0"
    
    # Dynamically determine the sysroot path based on the script's directory
    SYSROOT_PATH="$(dirname "$0")/../$TARGET_ARCH"
    
    CC="clang"
    CXX="clang++"
    
    FLAGS="-Qunused-arguments"
    FLAGS+=" --target=$TARGET_ARCH"
    FLAGS+=" --sysroot $SYSROOT_PATH/sysroot"
    FLAGS+=" -isystem $SYSROOT_PATH/include/c++/$GCC_VERSION/"
    FLAGS+=" -isystem $SYSROOT_PATH/include/c++/$GCC_VERSION/bits"
    FLAGS+=" -isystem $SYSROOT_PATH/include/c++/$GCC_VERSION/debug"
    FLAGS+=" -isystem $SYSROOT_PATH/include/c++/$GCC_VERSION/$TARGET_ARCH"
    
    FLAGS+=" -Wl,--sysroot=$SYSROOT_PATH/sysroot -L$SYSROOT_PATH/sysroot/usr/lib"
    FLAGS+=" -L $SYSROOT_PATH/../lib/gcc/$TARGET_ARCH/$GCC_VERSION"
    
    # Check whether clang or clang++ is called
    case $(basename "$0") in
      *clang) COMPILER="$CC" ;;
      *clang++) COMPILER="$CXX" ;;
      *) echo "Unknown compiler. Use clang or clang++." && exit 1 ;;
    esac
    
    exec "$COMPILER" $FLAGS "$@"

No source code modifications needed.

    $ uname -m
    x86_64
    $ file ld64/src/ld/ld
    ld64/src/ld/ld: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 4.4.1, with debug_info, not stripped

**Pull request closed without merging**
