### PR TITLE
Update cctools to 921, ld64 to 409.12

### PR DESCRIPTION
**Pull request by matthewbauer**
I've collected a few commits for updating cctools to the latest released version. The main ones are:

- 0fabae86ea42a0732db94676384120008eaf60ca
- b05484b1461b10db106b2c8448d29a8d0d26f508
- 389c115faa4745b585c7af5b965309c2285f8902

but i've tested this as a whole branch. Feel free to reuse as many of these commits as you think necessary!

Thanks to @martin31821 for help in getting Linux working.

### CODE REVIEW

**Comment by tpoechtrager** [comment]
Thank you for porting ld64 409.12 and cctools 921. I have added your branch.

**Comment by tpoechtrager** [comment]
You have removed **a lot** of fixes. Did you just copy & paste the files?

**Comment by tpoechtrager** [comment]
Thank you for your effort. I couldn't use your port because there were too many issues.

**Comment by martin31821** [comment]
> Thank you for your effort. I couldn't use your port because there were too many issues.

Can you elaborate a bit on what kind of issues you ran into? I'm using the cctools to build a native nodejs addon for OSX 10.14 on linux and it works fine for my use case.

**Comment by tpoechtrager** [comment]
It may just work fine for you. But in detail there were a lot of problems. For instance:

https://github.com/tpoechtrager/cctools-port/pull/65/commits/1caa5b8380c6cbbbf8fc8fa27ad420c92d28dc92 `mkpath` is not `mkpath_np`.

I also don't get what you are doing with `qsort_r` there. [This](https://github.com/tpoechtrager/cctools-port/blob/921-ld64-409.12/cctools/ld64/src/3rd/qsort_r.c#L418) is the `qsort_r` that's supposed to be used. Not the glibc one.

Also a lot of patches have been removed...

I am **thankful** for trying to upgrade cctools and ld64. But I had to re-do it.

PRs are always welcome!

**Comment by matthewbauer** [comment]
Ok no problem! I thought we kept most of them but definitely some may have been left off.

**Pull request closed without merging**
