### PR TITLE
codesign all arm64 binaries

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by beckermr** [comment]
Thank you @isuruf !

**Comment by tpoechtrager** [comment]
Have you tested the resulting binaries?

**Comment by isuruf** [comment]
Yes, the executables run now. (Although codesign -v on the executable says it is not) Earlier they were segfaulting.

**Comment by tpoechtrager** [comment]
Without ldid the binaries segfault on latest ARM64 macOS?

**Comment by beckermr** [comment]
> Without ldid the binaries segfault on latest ARM64 macOS?

Yes. All native binaries on osx arm64 have to be signed or they do not run. Running `install_name_tool` on a signed binary invalidates the signature.

**Comment by tpoechtrager** [comment]
I am amazed ldid actually works. Makes work so much easier. :)

**Comment by tpoechtrager** [comment]
I have merged your commits and did some additional work. Please verify everything still works.

**Comment by isuruf** [comment]
Yes, it works. Thanks

**Comment by isuruf** [comment]
@tpoechtrager, although it works fine on Linux, on macOS it fails with,
```
2020-10-04T18:07:46.6765850Z libtool: link: x86_64-apple-darwin13.4.0-clang++ -D__DARWIN_UNIX03 -Wall -Wno-long-long -Wno-import -Wno-format -Wno-deprecated -Wno-unused-variable -Wno-unused-private-field -Wno-unused-function -Wno-invalid-offsetof -Wno-int-conversion -Wno-char-subscripts -Wno-shift-negative-value -Wno-misleading-indentation -DLTO_SUPPORT -DTAPI_SUPPORT -D__LITTLE_ENDIAN__=1 -I$SRC_DIR/cctools/include -I$SRC_DIR/cctools/include/foreign -I$SRC_DIR/cctools/ld64/src -I$SRC_DIR/cctools/ld64/src/abstraction -I$SRC_DIR/cctools/ld64/src/3rd -I$SRC_DIR/cctools/ld64/src/3rd/BlocksRuntime -I$SRC_DIR/cctools/ld64/src/3rd/include -I$SRC_DIR/cctools/ld64/src/ld -I$SRC_DIR/cctools/ld64/src/ld/parsers -I$SRC_DIR/cctools/ld64/src/ld/passes -DPROGRAM_PREFIX=\"arm64-apple-darwin20.0.0-\" -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0 -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/cctools-and-ld64-530 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -O2 -gdwarf-4 -std=c++0x -isystem /usr/local/include -isystem /usr/pkg/include -stdlib=libc++ -DLD64_VERSION_NUM=530 -fblocks -isystem $PREFIX/include -pthread -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath -Wl,$PREFIX/lib -Wl,-rpath -Wl,$PREFIX/lib -Wl,-rpath -Wl,$PREFIX/lib -o ld ld-debugline.o ld-InputFiles.o ld-ld.o ld-Options.o ld-OutputFile.o ld-Resolver.o ld-Snapshot.o ld-SymbolTable.o ld-PlatformSupport.o code-sign-blobs/ld-blob.o -Wl,-rpath -Wl,$PREFIX/lib   -L$PREFIX/lib -L/usr/local/lib -L/usr/pkg/lib ../../../ld64/src/3rd/.libs/libhelper.a ../../../ld64/src/3rd/BlocksRuntime/.libs/libBlocksRuntime.a ../../../ld64/src/ld/parsers/.libs/libParsers.a ../../../ld64/src/ld/passes/.libs/libPasses.a -lxar -ldl -ltapi -pthread
2020-10-04T18:07:46.7075000Z ld: warning: directory not found for option '-L/usr/pkg/lib'
2020-10-04T18:07:46.8175930Z Undefined symbols for architecture x86_64:
2020-10-04T18:07:46.8176670Z   "_find_executable", referenced from:
2020-10-04T18:07:46.8178070Z       _main in ld-ld.o
2020-10-04T18:07:46.8201030Z ld: symbol(s) not found for architecture x86_64
2020-10-04T18:07:46.8212540Z clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by tpoechtrager** [comment]
Should be fixed.

**Pull request merged**
