### PR TITLE
Use sigtool's codesign binary to sign in install_name_tool and strip

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by tpoechtrager** [comment]
Awesome. Thank you.

Now I'd need someone to test produced binaries with a jailbroken iPhone.

**Comment by isuruf** [comment]
FWIW, I can confirm that this works fine on Apple Silicon where signatures are required.

**Comment by stephank** [comment]
This change causes `strip` to segfault in `strip_file` if it is used on a bad input:

```
strip: warning: can't process non-object and non-archive file: /src/bla.txt
zsh: segmentation fault  strip -S
```

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
  * frame #0: 0x0000000100002ff7 strip`strip_file + 3591
    frame #1: 0x0000000100001ed0 strip`main + 2112
    frame #2: 0x000000010003652e dyld`start + 462
```

This happens in Nix builds a lot, where `strip` is applied to just about everything, and the warning is simply ignored. In addition, crashing at that point causes it to leave behind a temporary `*.strip` file.

**Comment by stephank** [comment]
I created a fixed PR: https://github.com/tpoechtrager/cctools-port/pull/123

**Pull request merged**
