### PR TITLE
fix `as` when ccache is installed

### PR DESCRIPTION
**Pull request by Un1q32**
fixes https://github.com/tpoechtrager/cctools-port/issues/138

argv0 must be "clang" for ccache to run the compiler

https://github.com/tpoechtrager/cctools-port/pull/139 but rebased on the new version

### CODE REVIEW

**Comment by OldWorldOrdr** [comment]
bump

**Comment by OldWorldOrdr** [comment]
Mind taking a look at this?

**Comment by tpoechtrager** [comment]
Sorry, I will soon!

**Comment by Un1q32** [comment]
bump

**Comment by Un1q32** [comment]
bump 2

**Pull request closed without merging**
