### PR TITLE
Fix building on CentOS 7

### PR DESCRIPTION
**Pull request by abrodkin**
On attempt to build on CentOS 7 the following error happens:
```
In file included from opaque_section_file.cpp:29:
In file included from ../../../../ld64/src/ld/ld.hpp:31:
In file included from ../../../../include/foreign/unistd.h:1:
/usr/include/unistd.h:1147:35: error: __block attribute not allowed, only allowed on local variables
extern void encrypt (char *__block, int __edflag) __THROW __nonnull ((1));
                                  ^
In file included from lto_file.cpp:48:
In file included from ../../../../ld64/src/abstraction/MachOFileAbstraction.hpp:41:
In file included from ../../../../ld64/src/configure.h:5:
In file included from ../../../../include/foreign/unistd.h:1:
/usr/include/unistd.h:1147:35: error: __block attribute not allowed, only allowed on local variables
extern void encrypt (char *__block, int __edflag) __THROW __nonnull ((1));
```

That's due to the clash of `__block` usage between Clang and older glibc, see https://www.sourceware.org/bugzilla/show_bug.cgi?id=11157. And solution from https://www.sourceware.org/bugzilla/show_bug.cgi?id=11157#c6 is implemented here.

### CODE REVIEW

**Comment by tpoechtrager** [comment]
There's actually already a solution for that: https://github.com/tpoechtrager/cctools-port/blob/master/tools/fix_unistd_issue.sh. Remove that file and change `#       include_next "unistd.h"` to `#       include_next <unistd.h>` and I will merge it.

**Comment by abrodkin** [comment]
@tpoechtrager see if that's what you wanted me to do :)

**Comment by tpoechtrager** [comment]
Thanks!

**Comment by abrodkin** [comment]
@tpoechtrager is there a chance to get https://github.com/tpoechtrager/osxcross/blob/master/build.sh#L116 updated to point to this fix?

**Pull request merged**
