### PR TITLE
Implement corecrypto

### PR DESCRIPTION
**Pull request by lephilousophe**
This is a minimal implementation of ccdigest just enough for adhoc signing.
It should be OK for codesign but not sure as I don't own a Mac.

### CODE REVIEW

**Comment by tpoechtrager** [comment]
Awesome. Thank you!!

I can't test it either. I merged it. Let's see!

The macOS SDK doesn't seem to contain the CoreCrypto headers. Annoying.

**Comment by bruvzg** [comment]
At least on Intel mac (Big Sur 11.2.3), ad-hoc signatures produce by osxcross are not considered valid by `codesign` and third-party signature checkers (https://objective-see.com/products/whatsyoursign.html).

I have not tested it to run on M1 mac (executables with `ldid` fake signatures were non-functional).

Signature verification fails with following error:
```
> codesign -vvvv ./cross1

./cross1: code object is not signed at all
In architecture: arm64
```
Attempts to re-sign executable fails with:
```
> codesign -s "Apple Developer User ID" --options runtime ./cross1

./cross1: is already signed
```
It can be re-signed with `--force` flag and is fully functional afterwards.

Both command works successfully with the Xcode generated executable.
```
> codesign -vvvv ./mac1

./mac1: valid on disk
./mac1: satisfies its Designated Requirement
```

----

For the reference here are executables produced by https://github.com/tpoechtrager/osxcross/commit/dd4f8f329de5b5491cdfaded1c4ca6d12fbcd997 and Xcode 12.4 (12D4e), from the following source:
```c++
int main() {
	return 0;
}
```

Archive with the test executables: [codesign.zip](https://github.com/tpoechtrager/cctools-port/files/6217508/codesign.zip)

| File   | Description                                                                                              | Signature is valid? | Can be re-signed without `--force` flag? |
| -------| -------------------------------------------------------------------------------------------------------- | ------------------- | ---------------------------------------- |
| mac1   | Compiled with Xcode, `clang++ -arch arm64 ./a.cpp -o mac1`                                               | YES                 | YES                                      |
| mac0   | Copy of `mac1` with signature removed by `codesign --remove-signature ./mac0` command                    | NO                  | YES                                      |
| mac2   | Copy of `mac0` with ad-hoc signature added by `codesign -s - ./mac2` command                             | YES                 | NO                                       |
| cross1 | Compiled with osxcross, `aarch64-apple-darwin20.2-clang++ ./a.cpp -o cross1`                             | NO                  | NO                                       |
| cross0 | Copy of `cross1` with signature removed by `codesign --remove-signature ./cross0` command                | NO                  | YES                                      |
| cross2 | Copy of `cross0` with linker signature added by `codesign -s - --options linker-signed ./cross2` command | YES                 | YES                                      |

**Comment by lephilousophe** [comment]
cross1 file has been signed by ldid and not by code from this PR.
You can see it by looking at flags: with this PR, flags are 0x2002 like Xcode clang++.
osxcross master branch doesn't make use of this PR yet. testing branch does.

**Comment by bruvzg** [comment]
> osxcross master branch doesn't make use of this PR yet. testing branch does.

Ah, I see, `testing` branch signatures works correctly (pass validation, and are re-signable without issues).

**Comment by tpoechtrager** [comment]
That's great!

However, we need to find a new solution for `lipo`, `strip` and so if `ldid` doesn't work. :/

**Comment by lephilousophe** [comment]
Upstream ldid (https://git.saurik.com/ldid.git) has some patches but not yet working.
Plus, ldid is still needed when signing a whole bundle.
cctools signature just considers the built binary

**Comment by bruvzg** [comment]
> However, we need to find a new solution for lipo, strip and so if ldid doesn't work. :/

`lipo` seems to work fine. Full executable is not passing validation (because of x86_64 part), but arm64 part (`codesign -vvvv -a arm64 ./name`) is still valid. It's exactly the same result as with Xcode `lipo`.

**Comment by tpoechtrager** [comment]
But `strip` breaks the signatures. Right?

**Comment by bruvzg** [comment]
> But strip breaks the signatures. Right?

Yes. And `install_name_tool` probably have the same issue.

Xcode `strip` break real ID (`codesign -s ID`) and ad-hoc (`codesign -s -`) signatures, but preserve linker-signed one.

**Comment by tpoechtrager** [comment]
I removed the ldid fake signing code. It was a stupid idea anyway.
`-Wl,-adhoc_codesign` is now enabled by default for the iOS toolchain.

**Comment by isuruf** [comment]
With latest cctools-port, `install_name_tool` breaks the signatures. However, the `install_name_tool` that comes with macOS doesn't break the signature

**Comment by tpoechtrager** [comment]
cctools code signing is not implemented. `install_name_tool` belongs to cctools.

**Comment by isuruf** [comment]
Is there anything I can do to help?

**Comment by tpoechtrager** [comment]
You could test whether https://git.saurik.com/ldid.git works now for macOS.

**Comment by isuruf** [comment]
Sure. ldid works fine on macOS arm64. Only issue is that executables that ldid signed are not shown as signed when querying through `codesign`.

I've also tried out https://github.com/thefloweringash/sigtool and it works too. Two advantages over ldid is that `codesign` can verify executables signed using `sigtool` and `sigtool` has a more permissive license.

**Comment by tpoechtrager** [comment]
Awesome. Thank you! I will go with `sigtool` then.

**Comment by tpoechtrager** [comment]
I assume `sigtool` can also be used as a replacement for `ldid`?

**Comment by isuruf** [comment]
I've no clue about jailbroken iOS devices. I can only confirm that `sigtool` signed binaries run on M1s.

**Pull request merged**
