### PR TITLE
better otool wrapper

### PR DESCRIPTION
**Pull request by Un1q32**
The main change is that it tries `otool` first, then `llvm-otool` if that fails.  This fixes the otool wrapper on macOS, where `llvm-otool` isn't in PATH but `otool` is.

### CODE REVIEW

**Comment by Un1q32** [comment]
bump

**Comment by Un1q32** [comment]
bump 2

**Comment by Un1q32** [comment]
It's worth noting that this won't matter too much if cctools 1010.6 is merged, since it brings back Apple's otool.  Would still be nice for anyone who needs 1009.2 in particular for whatever reason.

**Comment by tpoechtrager** [comment]
I never merged this because it could theoretically lead to a fork bomb. When the otool wrapper is installed without a host prefix it would execute itself infinitely.

**Comment by Un1q32** [comment]
> I never merged this because it could theoretically lead to a fork bomb. When the otool wrapper is installed without a host prefix it would execute itself infinitely.

I don't think that would be a forkbomb, since there is no fork(), just exec(), so it wouldn't crash a system, but it's still true that it would be a bug

**Comment by Un1q32** [comment]
Yeah it just pins one cpu core until interrupted, I could mod it to use known absolute paths for otool but now that real otool sources are back in 1010.6 I don't see much point.

**Pull request closed without merging**
